apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-backend
  namespace: shared-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-backend
  template:
    metadata:
      labels:
        app: shared-backend
    spec:
      containers:
        - name: backend
          image: hashicorp/http-echo
          args:
            - "-text=Shared Internal Service"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: shared-backend
  namespace: shared-services
spec:
  selector:
    app: shared-backend
  ports:
    - port: 80
      targetPort: 5678
