# this file was written mostly for experimenting with network policies and traffic routes. it does not need to be applied right now. shared service namespace is not meant to restrict 
# any incoming or outgoing traffic at present.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-dev-namespaces
  namespace: shared-services
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: dev-sarthak
        - namespaceSelector:
            matchLabels:
              name: dev-aman
