apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev-aman
spec:
  hard:
    pods: "2"
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "500m"
    limits.memory: "512Mi"
