apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: dev-sarthak
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
